name: Change Target Branch on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - updated

jobs:
  change-target-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Change Target Branch
      run: |
        # Set the new target branch name
         


        echo $GITHUB_REF
        target=$TARGET_BRANCH
        token=${{ secrets.TOKEN }}
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN {FS="/"} {print $3}')

        PR_JSON=$(curl "https://api.github.com/repos/kamal-devtron/action/pulls/$PR_NUMBER")
        curl "https://api.github.com/repos/kamal-devtron/action/branches" > branch.json
        echo $BRANCHES

        jq -c '.[].name' branch.json | while read i; do
        echo $i
        done 

        if echo "$BRANCHES" | jq -e ".[] | select(.name == "release-candidate")" > /dev/null; then
          echo "Branch $BRANCH_NAME exists"
          echo "::set-output name=branch_exists::true"
        else
          echo "Branch $BRANCH_NAME does not exist"
          echo "::set-output name=branch_exists::false"
        fi           

        SOURCE_BRANCH=$(echo $PR_JSON | jq -r '.head.ref')
        REPO=$(echo $PR_JSON | jq -r '.head.repo.full_name')
        echo $SOURCE_BRANCH
        echo $REPO
       
        echo $token

        curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  -H "Authorization: Bearer $token" \
         https://api.github.com/repos/$REPO/pulls/1 -d '{"base": "${{ secrets.TARGET_BRANCH }}"}'
        
      env:
        TARGET_BRANCH: ${{ secrets.TARGET_BRANCH }}
