name: Change Target Branch on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  change-target-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Change Target Branch
      run: |
        # Set the new target branch name

        set -ex
        NEW_TARGET_BRANCH="release-candidate-branch"
        echo $GITHUB_REF

        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN {FS="/"} {print $3}')

        echo $PR_NUMBER

        PR_JSON=$(curl "https://api.github.com/repos/kamal-devtron/action/pulls/$PR_NUMBER")

        SOURCE_BRANCH=$(echo $PR_JSON | jq -r '.head.ref')
        REPO=$(echo $PR_JSON | jq -r '.head.repo.full_name')
        echo $SOURCE_BRANCH
        echo $REPO

        curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  -H "Authorization: Bearer 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" \
         https://api.github.com/repos/$REPO/pulls/1 -d '{"base": "release-candidate"}'
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
