name: Change Target Branch on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  change-target-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Change Target Branch
      run: |
        # Set the new target branch name
        NEW_TARGET_BRANCH="release-candidate-branch"
        echo $GITHUB_REF

        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN {FS="/"} {print $3}')

        echo $PR_NUMBER
        echo $github.repository


        PR_JSON=$(curl "https://api.github.com/repos/kamal-devtron/action/pulls/$PR_NUMBER")


        PR_JSON=$(curl "https://api.github.com/repos/kamal-devtron/action/pulls/$PR_NUMBER")

        SOURCE_BRANCH=$(echo $PR_JSON | jq -r '.head.ref')
        REPO= $(echo $PR_JSON | jq -r '.head.repo.full_name')

        # Update the target branch of the PR using GitHub API
        curl -s -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -d "{\"base\":\"$NEW_TARGET_BRANCH\"}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
